version: '3'
services:
  janus:
    image: ivadim/fruitnanny-janus
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - ./configuration/janus:/etc/janus
      - ./configuration/ssl:/etc/fruitnanny-ssl
    expose:
      - 8088 # api http
      - 8089 # api https
      - 5002 # audio
      - 5004 # video

  gstreamer-stream:
    image: ivadim/fruitnanny-gstreamer
    restart: always
    privileged: true
    network_mode: "host"
    depends_on:
      - janus
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./bin/gstreamer.sh:/bin/gstreamer.sh:ro
    devices:
      - "/dev/vchiq:/dev/vchiq"
    command: /bin/gstreamer.sh

  fruitnanny:
    image: ivadim/fruitnanny-app
    restart: always
    privileged: true
    volumes:
      - ./fruitnanny_config.js:/opt/fruitnanny/fruitnanny_config.js
      - ./bin:/opt/fruitnanny/bin
    network_mode: "host"
    depends_on:
      - janus
    expose:
      - 7000

  nginx:
    image: arm32v6/nginx:alpine
    restart: always
    network_mode: "host"
    depends_on:
      - janus
      - fruitnanny
    volumes:
      - ./configuration/nginx/fruitnanny_http:/etc/nginx/conf.d/default.conf
      - ./configuration/nginx/fruitnanny_https:/etc/nginx/conf.d/default-ssl.conf
      - ./configuration/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./configuration/ssl:/etc/fruitnanny-ssl
    ports:
      - "80:80"
      - "443:443"
